### ISSUE TITLE
index_(lock_free_array) and index_columns_(vector), drop index bug

### ISSUE THREAD

**Issue by mengranwo** [AngLi-Leon/peloton#5]
Since we don't support drop index, then we don't have bugs

  // Drop the index, instead of clear index, set it to nullptr
  indexes_.Update(index_offset, nullptr);

  // Drop index column info
  // BUG!! don't erase vector element, won't align
  indexes_columns_.erase(indexes_columns_.begin() + index_offset);

**Comment by AngLi-Leon** [comment]
This bug is in storage level....

**Comment by camellyx** [comment]
Fixed now.
