### ISSUE TITLE
index scan cannot find tuple

### ISSUE THREAD

**Issue by camellyx** [AngLi-Leon/peloton#9]
We created unique index on pg_table (table_name, database_oid).
The result of the second select statement is wrong.

postgres=# select * from pg_catalog.pg_table;
 table_oid |  table_name  | database_oid 
-----------+--------------+--------------
  33554432 | pg_database  |     16777216
  33554433 | pg_table     |     16777216
  33554434 | pg_index     |     16777216
  33554435 | pg_attribute |     16777216
(4 rows)

postgres=# select * from pg_catalog.pg_table where table_name='pg_table';
 table_oid | table_name | database_oid 
-----------+------------+--------------
(0 rows)

postgres=# select * from pg_catalog.pg_table where table_name='pg_table' and database_oid=16777216;
 table_oid | table_name | database_oid 
-----------+------------+--------------
  33554433 | pg_table   |     16777216
(1 row)

**Comment by camellyx** [comment]
The original example is fixed, but similar query on pg_index still has problem, why?

postgres=# select * from pg_catalog.pg_index where index_name='pg_database_pkey';
 index_oid | index_name | table_oid | index_type | index_constraint | unique_keys 
-----------+------------+-----------+------------+------------------+-------------
(0 rows)

postgres=# select * from pg_catalog.pg_index where index_name='pg_database_pkey' and table_oid=33554432;
 index_oid | index_name | table_oid | index_type | index_constraint | unique_keys 
-----------+------------+-----------+------------+------------------+-------------
(0 rows)
Fixed https://github.com/AngLi-Leon/peloton/commit/479aa6d7a7a315f01593acafc6989e8b3af02105

**Comment by camellyx** [comment]
This must be our index creation problem.

postgres=# select * from pg_catalog.pg_index where table_oid=33554432;
 index_oid | index_name | table_oid | index_type | index_constraint | unique_keys 
-----------+------------+-----------+------------+------------------+-------------
(0 rows)

**Comment by mengranwo** [comment]
I think it has something to do with the terminal failed to display boolean type attribute.
Maybe we have successfully select the corresponding tuples but unable to print on terminal.

Fixed https://github.com/cmu-db/peloton/pull/598

**Comment by camellyx** [comment]
Fixed!!!
